### ISSUE TITLE
Hard to write project creation directory correctly

### ISSUE THREAD

**Issue by haaakon** [BeiningBogen/silver-platter#6]
I dragged folder to write a correct file url where i wanted to put my project,
had an existing folder there, so the url is correct

```
./install.sh
Project name (no spaces): TEST
Project path: /Users/bogen/dev/silver-platter/myproject
```

output:

```
Install TEST in /Users/bogen/dev/silver-platter/myprojectTEST ? yes
Copying xcode template to /Users/bogen/dev/silver-platter/myprojectTEST
```

it seems there are problems with the way it is parsing directory to create. Could it maybe see if the url is correct before creating the project? Alot to clean up if it broke

**Comment by fonsim** [comment]
This issue is addressed in #8.
